version: '3'
services:
  db:
    container_name: portfolio-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=portfolio_app
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
