name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.REPOSITORY_OWNER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push the frontend docker image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.frontend
          push: true
          tags: |
            ${{ github.REPOSITORY }}-frontend:latest
            ${{ github.REPOSITORY }}-frontend:${{ github.SHA }}

      - name: Build and push the backend docker image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.backend
          push: true
          tags: |
            ${{ github.REPOSITORY }}-backend:latest
            ${{ github.REPOSITORY }}-backend:${{ github.SHA }}
  deploy:
    name: Deploy
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://simohin.tplinkdns.com:16443
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          action: deploy
          namespace: default
          strategy: basic
          manifests: |
            .k8s/ingress.yml
            .k8s/deployment.yml
            .k8s/service.yml
