name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ GITHUB_REPOSITORY_OWNER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push the frontend docker image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.frontend
          push: true
          tags: |
            ${{ GITHUB_REPOSITORY }}-frontend:latest
            ${{ GITHUB_REPOSITORY }}-frontend:${{ GITHUB_SHA }}

      - name: Build and push the backend docker image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.backend
          push: true
          tags: |
            ${{ GITHUB_REPOSITORY }}-backend:latest
            ${{ GITHUB_REPOSITORY }}-backend:${{ GITHUB_SHA }}
