name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: frontend
        run: flyctl deploy -c fly.frontend.toml --dockerfile Dockerfile.frontend --ignorefile .dockerignore.frontend --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: backend
        run: flyctl deploy -c fly.backend.toml --dockerfile Dockerfile.backend --ignorefile .dockerignore.backend --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
