name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-frontend:
    name: Deploy frontend
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: frontend
        run: flyctl deploy -c frontend/fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: backend
        run: flyctl deploy -c backend/fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
